### ISSUE TITLE
Error 400 when the service name contains a space

### ISSUE THREAD

**Issue by brokenbuddha** [Operator873/Nagios-Discord#2]
https://github.com/Operator873/Nagios-Discord/blob/ef83250b85330dbcd667d9cac45faae682362e19/send-service.py#L28C109-L28C109

This seems to have some issues if the service name contains a space and causes discord to return an error 400.

It can be fixed by replacing white spaces with a "+" using something like this:

link = f"https://{DOMAIN}/nagios/cgi-bin/extinfo.cgi?type=2&host={data['host']}&service={data['servdesc'].replace(' ', '+')}"

**Comment by Operator873** [comment]
Hello @brokenbuddha and thanks for the suggestion.

I don't use Nagios so I can't test these changes. But I have pushed changes that URL encodes host and service names so it should be clickable. Can you pull and test for me?

**Comment by brokenbuddha** [comment]
I'm having some issues getting urllib to work on my centos 8 with python 3.6.8 and I'm still trying to figure out what the problem is but I will try an fix it so I can test, cheers.

The error is "TypeError: 'module' object is not callable".
